# Generated by Django 5.1.5 on 2025-02-20 12:08

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='airline_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='cards/images')),
                ('alt', models.CharField(max_length=255)),
                ('href', models.URLField()),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Cards',
                'db_table': 'cards',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='cities/')),
                ('price', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='features/images')),
                ('alt', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Features',
                'db_table': 'features',
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='flight_images/')),
                ('title', models.CharField(max_length=255)),
                ('destinations', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ImageCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='imagescard/images')),
                ('alt', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Image Cards',
                'db_table': 'image_cards',
            },
        ),
        migrations.CreateModel(
            name='OfferAvailable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('phone_img', models.ImageField(blank=True, null=True, upload_to='offer_images/')),
            ],
        ),
        migrations.CreateModel(
            name='CityDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='flight.city')),
            ],
        ),
        migrations.CreateModel(
            name='FlightOffer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('expiresOn', models.DateField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('btn_title', models.CharField(blank=True, max_length=150, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('about', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('terms', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('image', models.ImageField(blank=True, null=True, upload_to='offers/')),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('discount', models.CharField(blank=True, max_length=255, null=True)),
                ('discount_international', models.CharField(blank=True, max_length=255, null=True)),
                ('minBooking', models.CharField(blank=True, max_length=50, null=True)),
                ('minBooking1', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_icon', models.ImageField(blank=True, null=True, upload_to='bank_icons/')),
                ('card_icon', models.FileField(blank=True, null=True, upload_to='card_icons/')),
                ('card_title', models.CharField(blank=True, max_length=150, null=True)),
                ('offer_available', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_offer', to='flight.offeravailable')),
            ],
        ),
    ]
