# Generated by Django 5.1.2 on 2025-02-07 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='items/images')),
                ('alt', models.CharField(max_length=255)),
                ('href', models.URLField()),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'items',
                'db_table': 'items',
            },
        ),
    ]
