# Generated by Django 5.1.2 on 2025-02-07 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='height',
        ),
        migrations.RemoveField(
            model_name='service',
            name='width',
        ),
    ]
